### ISSUE TITLE
Flaky test 

### ISSUE THREAD

**Issue by cdluv** [floyernick/Data-Structures-and-Algorithms#5]
https://github.com/floyernick/Data-Structures-and-Algorithms/blob/6ae8c0f2e09c371f47f2a3c76f3b73989e4f3c45/BinarySearch/BinarySearch_test.go#L21

- This line could generate the number 0 in which case it would pass without making any verifications. suggest you add 10 to get some numbers.

**Comment by floyernick** [comment]
Thanks for the remark! Now it is fixed :)
