### ISSUE TITLE
Make repo go get-able by adding a .go file to top folder level

### ISSUE THREAD

**Issue by philipithomas** [floyernick/Data-Structures-and-Algorithms#6]
You need to make the top level of the repo a Go package in order to make it `go get`-able. Otherwise, it returns an error:

```sh
package github.com/floyernick/Data-Structures-and-Algorithms: no Go files in /Users/philip/src/github.com/floyernick/Data-Structures-and-Algorithms
```

It can as simple as a package declaration and it will work, i.e. in new file `dsa.go` at the top level of the package, just have a single line of `package dsa` and you're good to go.

**Comment by floyernick** [comment]
Fixed! ;)
